export enum SUBJECT_VECTOR {
  WPVP = 'WPVP',
  PVP = 'PVP',
  PVE = 'PVE',
  CLASS_HALL = 'CLASS-DISCORD',
  COMMON = 'COMMON',
  UNCLASSIFIED = 'UNCLASSIFIED',
}

export enum FEFENYA_STORAGE_KEYS {
  GOTD_TOD_STATUS = 'GOTD_TOD_STATUS',
  GOTD_TOD_SUMMARY_STATUS = 'GOTD_TOD_SUMMARY_STATUS',
}

export enum FEFENYA_TEXT_KEYS {
  ALREADY_TRIGGERED = 'ALREADY_TRIGGERED',
}

export enum FEFENYA_COMMANDS {
  GOTD = 'gay',
  GOTS_STATS = 'gaylords',
}
